### ISSUE TITLE
Define viewing-sequence of presentation

### ISSUE THREAD

**Issue by irisSchaffer** [ostera/unveil.js#22]
This should be a method on the router that returns the `next` or `previous` slide. How do we map `up`/`down`, `left`/`right`?

--- A
----- A1
----- A2
--- B
----- B1
----- B2

Ramblings:
- if we are on `A1`. We want to go to `B1`. Do you press `right`?
- if we are on `B2`. We want to go to `B1`. Do we press `up` or `left`?

**Comment by leostera** [comment]
As part of a new state, we should include the possible directions on which to go from there. I don't think directional words would make sense here if we take into account more than 2 dimensiones.

A more generic state would look like this:

``` js
State {
  current: [ 0, 1, ...],
  directions: [
     {next: true,  previous: false}, // for first index
     {next: false, previous: false}, // for second index
     ...
  ]
}
```

This is very easily traversed to see if we have directions available in any dimension. A set of 4 arrows to move in a 2-dimensional map could alias like this:

``` js
let canGoLeft  = state.directions[0].previous;
let canGoRight = state.directions[0].next;
let canGoUp    = state.directions[1].previous;
let canGoDown  = state.directions[1].next;
```

And use that to highlight, or disable the rendered arrows.

Similarly, if the presentation had 3 dimensions:

``` js
let canGoIn  = state.directions[2].previous;
let canGoOut = state.directions[2].next;
```

So maybe this can be mapped at the `UnveilApp` level and passed to the relevant controls as:

``` js
Directions {
  up:    true,
  left:  false,
  down:  false,
  right: false
}
```

**Comment by irisSchaffer** [comment]
Alright. Let's look at it from this perspective:
I want to click or type `enter` to get the _next_ slide, whichever one that might be. This is really more about the user experience than the technicality of how to represent that move.
Do I have to click `down` to get to the next subslide? will a `right` take me from `A1` to `B1` etc.?

**Comment by leostera** [comment]
It would be counter-intuitive to allow a `right` to move through the first index while preserving the second one.

Most slides work from left to right, and only use down to add depth on a topic. So in a tree like the one you posted:

```
--- A
----- A1
----- A2
--- B
----- B1
----- B2
```

The typical order will be: `A A1 A2 B B1 B2`

In any case providing a `jump` feature should be enough to account for `A A1 B1` or any non-linear flow. In which ase, the actual `map` of the slides is available at the `UnveilApp` level and could be passed into the component if needed.

**Comment by irisSchaffer** [comment]
Note: there is no `A`. `A` will directly lead you to `A1`.

```
--- A
----- A1
----- A2
--- B
--- C
----- C1
----- C2
```

So this would be: `A1 A2 B C1 C2`.

> It would be counter-intuitive to allow a right to move through the first index while preserving the second one.

It's more about what should happen if you're on `A1` and go `right`. Will that be `B` then or `A2`? I guess subslides will be the exception and not the norm, in which case it would make sense to go from `A1` to `B` and leaving out potential subslides. Another way would be to go and visit all slides, no matter what, in which case the question is how you get out of a subtree again.

**Comment by leostera** [comment]
Okay, I think I understand you better. If you're on `A1` (or `A2`) and press `right`, you should end up in `B`. Then pressing `right` again will take you to `C1`.

Pressing `left` on any `C` sub-slides should take you back to `B`.

The idea was that the first subslide is treated as the top-level slide, so `A1` will be, to any practical ends, `A`, right?
