### ISSUE TITLE
Define Controller interface

### ISSUE THREAD

**Issue by leostera** [ostera/unveil.js#25]

**Comment by leostera** [comment]
Provisionally we can define a controller interface that gets passed both a `next` and a `previous` function handlers as required parameters. I know how much @irisSchaffer likes classes, most of the behavior defined in a controller should be defined in a `Controller` mixin :smile: 

So:
- [ ] Controller mixin that checks for `propTypes` and ensures the interface 
- [ ] Define `next` and `previous` functions signatures or which other handlers should be passed in

**Comment by irisSchaffer** [comment]
>  Define next and previous functions signatures or which other handlers should be passed in

Not entirely sure about this point. How do you see this working?

**Comment by leostera** [comment]
Closed here https://github.com/ostera/unveil.js/commit/6cc1b5d33e5b9042c1a9b4f6a279656732bf18be
