### ISSUE TITLE
Presenter

### ISSUE THREAD

**Issue by irisSchaffer** [ostera/unveil.js#41]
We should start thinking about the interface of the presenter. What does a presenter need?
We will likely have an own presenter for things like the overview, so it need so have access to all slides. At the same time it needs to know what the current slide is (I'm thinking indices). For things like a presenter-view, knowledge of what the next slide is would be very useful. Same with the thing we discussed at some point, where the next and previous slide are partly visible.
Inputs @ostera ?

**Comment by leostera** [comment]
I like the idea of a presenter receiving all available slides, and a pointer of the current ones. Then it can decide which ones to show, or how many to show, and how to show them.

``` js
const options = {
  slides: this.slides,
  current: this.state.currentSlide,
  mode: this.mode,
  // some other stuff here
};

<Presenter {...options} />
```

**Comment by irisSchaffer** [comment]
I have a feeling the mode shouldn't be in there, the mode will define the Presenter and not the other way round

**Comment by leostera** [comment]
Yeah, I lost it for a second there. According to the `mode` we use one or another `Presenter`.

**Comment by irisSchaffer** [comment]
Closed as per https://github.com/ostera/unveil.js/commit/b96a2eb593499b22de019a0363a03e6d9ea69714
