### ISSUE TITLE
UIControls: Indicate movement

### ISSUE THREAD

**Issue by irisSchaffer** [ostera/unveil.js#52]
Just a thought: It feels a bit weird to use the keys or swipe when there is no visual feedback on the arrows.
We might consider flashing the arrows black if we move right/left/up/down, even when we don't use them to navigate. @ostera ?

**Comment by leostera** [comment]
I think the visual hint should be different on mobile. I'm thinking a colored line on the side that's available could look good. We can try it out cheaply too
