### ISSUE TITLE
Add utility for is(ComponentName, element)

### ISSUE THREAD

**Issue by irisSchaffer** [ostera/unveil.js#68]
Instead of having this function in `Slide`, we should really have a general one which takes the name of the react component and the element.

**Comment by leostera** [comment]
:+1:

**Comment by leostera** [comment]
Should we extend the default base component returned by React? Should we add a new `.is` method to the `React` object? How'd you like to provide this?

**Comment by leostera** [comment]
We could also extend the component to have an `is` method that would automatically use it's name, so we can do:

`Slide.isSlide(element)` and if the element has the proper displayName then it'll return true.

But this could work for any other components: `Presenter.isPresenter(element)` or `Link.isLink(element)`

A rough implementation would do something like:

``` js
this[`is#{this.type.displayName}`] = (e) => {
  return React.isValidElement(e) && e.type.displayName === this.type.displayName
}
```
